Repository NextCamp-8B/8B-SF, pull requests merged in 2024-06, with the labels that each got.

#10 feat#7 : togglebutton 기능
  src/components/shared/ToggleButton.tsx
Labels: ✨ Feature

#8 feat#2: Badge 컴포넌트 구현
  src/components/shared/Badge.tsx
Labels: ✨ Feature

#16 [#15] 원격저장소 파일 및 폴더명 대소문자 변경
  src/components/shared/dropdown/DeropdownLabel.tsx
  src/components/shared/dropdown/DropdownOption.tsx
  src/components/shared/dropdown/DropdownPanel.tsx
  src/components/shared/dropdown/DropdownSelect.tsx
  src/components/shared/dropdown/DropdownWrapper.tsx
  src/components/shared/input/InputCore.tsx
  src/components/shared/input/InputCoreWrapper.tsx
  src/components/shared/input/InputDuplicateCheck.tsx
  src/components/shared/input/InputLabel.tsx
  src/components/shared/input/InputMain.tsx
  src/components/shared/popup/PopupContents.tsx
  src/components/shared/popup/PopupDimmedLayer.tsx
  src/components/shared/popup/PopupMain.tsx
  src/components/shared/popup/PopupTitle.tsx
Labels: 🐞 BugFix

#20 feat #12 : Card 컴포넌트 제작
  src/app/hun/page.tsx
  src/components/shared/Card.tsx
Labels: ✨ Feature

#21 [#11] 로딩 스피너 구현
  src/app/han/page.tsx
  src/components/shared/Badge.tsx
  src/components/shared/LoadingSpinner.tsx
  src/components/shared/NewsListItem.tsx
  src/components/shared/StockListItem.tsx
Labels: ✨ Feature

#24 feat #23 : 페이지 라우트 설정
  package.json
  src/app/(after)/home/page.tsx
  src/app/(after)/layout.tsx
  src/app/(after)/news/page.tsx
  src/app/(after)/search/page.tsx
  src/app/(after)/stock/page.tsx
  src/app/(after)/user/page.tsx
  src/app/(before)/find/id/page.tsx
  src/app/(before)/find/pw/page.tsx
  src/app/(before)/login/page.tsx
  src/app/(before)/signup/page.tsx
  src/app/(tmp)/example/page.tsx
  src/app/(tmp)/han/page.tsx
  src/app/(tmp)/hun/page.tsx
  src/constants.ts
  src/hooks/example.ts
  src/utils/example.ts
  yarn.lock
Labels: ✨ Feature

#26 버튼 컴포넌트 구현
  src/assets/icons/us.svg
  src/components/shared/buttons/ButtonBase.tsx
  src/components/shared/buttons/FabButton.tsx
  src/components/shared/buttons/IconButton.tsx
  src/components/shared/buttons/IconButtonBase.tsx
  src/components/shared/buttons/LanguageButton.tsx
  src/components/shared/buttons/TextButton.tsx
  src/components/shared/buttons/types.ts
Labels: ✨ Feature

#35 feat #34 : Card 컴포넌트 수정
  src/app/(tmp)/hun/page.tsx
  src/components/shared/Card.tsx
Labels: ✨ Feature

#40 feat #39 : Card-3 분리
  src/app/(tmp)/hun/page.tsx
  src/components/shared/Card.tsx
Labels: ✨ Feature

#42 bug #41 : Card css 수정
  src/app/(tmp)/hun/page.tsx
  src/components/shared/Card.tsx
Labels: 🐞 BugFix

#46 feat #45 : 랜딩 패이지 UI 구현
  src/app/(landing)/layout.tsx
  src/app/(landing)/page.tsx
  src/app/page.tsx
  src/assets/landing/background.png
  src/assets/landing/device.png
  src/assets/landing/device_screen.png
  src/assets/landing/mockup.png
Labels: ✨ Feature

#48 feat #33 : login 페이지 구현
  src/app/(before)/login/page.tsx
  src/assets/icons/google_logo.svg
  src/assets/icons/kakao_logo.svg
  src/assets/icons/naver_logo.svg
  src/components/shared/Checkbox.tsx
  src/components/shared/buttons/ButtonBase.tsx
  src/components/shared/buttons/IconButton.tsx
  src/components/shared/buttons/types.ts
Labels: ✨ Feature

#47 feat #36 : header
  src/app/(after)/layout.tsx
  src/app/(before)/layout.tsx
  src/app/(landing)/layout.tsx
Labels: ✨ Feature

#51 feat #49 : header zindex
  src/app/(after)/layout.tsx
  src/app/(before)/layout.tsx
Labels: ✨ Feature

#55 feat #54 : recent 폴더 구조 변경 및 hover 추가
  src/app/(after)/home/page.tsx
  src/components/recent/NoData.tsx
  src/components/recent/Recent.tsx
  src/components/recent/RecentItem.tsx
Labels: ✨ Feature

#58 feat #50 : 아이디 찾기 페이지Ui 구현
  src/app/(before)/find/id/page.tsx
  src/app/(before)/login/page.tsx
  src/components/shared/buttons/ButtonBase.tsx
  src/components/shared/buttons/FabButton.tsx
  src/components/shared/buttons/IconButton.tsx
  src/components/shared/buttons/IconButtonBase.tsx
  src/components/shared/buttons/LanguageButton.tsx
  src/components/shared/buttons/TextButton.tsx
  src/components/shared/buttons/types.ts
Labels: ✨ Feature

#61 feat #59 : 비밀번호 찾기 페이지UI 구현
  src/app/(before)/@modal/(.)find/pw/modal/page.tsx
  src/app/(before)/@modal/default.tsx
  src/app/(before)/find/id/page.tsx
  src/app/(before)/find/pw/page.tsx
  src/app/(before)/layout.tsx
Labels: ✨ Feature

#63 feat #57 : Stock type path, id 추가
  src/app/(after)/home/page.tsx
  src/components/recent/Recent.tsx
  src/components/recent/RecentItem.tsx
Labels: ✨ Feature

#66 feature #62 : NotFound / 로딩 페이지 UI 구현
  src/app/loading.tsx
  src/app/not-found.tsx
Labels: ✨ Feature

#68 feat #64 : 발견 페이지 초기 화면 구현
  src/app/(after)/search/page.tsx
  src/components/search/DeleteSearch.tsx
  src/components/search/InputItem.tsx
  src/components/search/NoSearchData.tsx
  src/components/search/PopularItem.tsx
  src/components/search/PopularSearch.tsx
  src/components/search/RecentSearch.tsx
  src/utils/date.ts
Labels: ✨ Feature

#73 feat #72 : 최신뉴스 - 무한스크롤 기능 추가
  package.json
  src/components/news/RecentNews.tsx
  yarn.lock
Labels: ✨ Feature

#75 feat #69 : 발견 페이지 검색 기능 UI 구현
  src/app/(after)/layout.tsx
  src/app/(after)/search/page.tsx
  src/components/recent/RecentItem.tsx
  src/components/search/FindNews.tsx
  src/components/search/FindStock.tsx
  src/components/search/FindStockItem.tsx
  src/components/search/InputItem.tsx
  src/components/search/MoreData.tsx
  src/components/search/NewsItem.tsx
  src/components/search/NoSearchData.tsx
  src/components/search/NotFind.tsx
  src/components/search/PopularItem.tsx
  src/components/search/PopularSearch.tsx
  src/components/search/RecentSearch.tsx
  src/components/search/SearchHeading.tsx
  src/components/search/SearchLabel.tsx
  src/constants.ts
Labels: ✨ Feature

#78 refact #77 : button컴포넌트 수정
  src/components/shared/buttons/IconButton.tsx
  src/components/shared/buttons/IconButtonBase.tsx
  src/components/shared/buttons/TextButton.tsx
  src/components/shared/buttons/types.ts
Labels: 🔨 Refactor

#80 refact #79 : 비밀번호 찾기 임시비밀번호 발급 팝업 경로 수정
  src/app/(before)/find/pw/page.tsx
  src/app/p/@modal/default.tsx
  src/app/p/@modal/find/pw/page.tsx
  src/app/p/find/pw/page.tsx
  src/app/p/layout.tsx
  src/components/findPw/Popup.tsx
Labels: 🔨 Refactor

#82 refact #81 : 회원가입 페이지UI 수정
  src/app/(before)/signup/page.tsx
  src/assets/icons/pencil.svg
  src/components/signup/Agreement.tsx
  src/components/signup/AgreementBox.tsx
  src/components/signup/Auth.tsx
  src/components/signup/ProfileSetup.tsx
  src/components/signup/SignupForm.tsx
Labels: 🔨 Refactor

#83 feat #71 : 설정 페이지 UI 구현
  src/app/(after)/user/page.tsx
  src/app/(before)/signup/page.tsx
  src/components/signup/Agreement.tsx
  src/components/signup/Auth.tsx
  src/components/signup/ProfileSetup.tsx
  src/components/signup/SignupForm.tsx
  src/components/user/CheckPassword.tsx
  src/components/user/LanguageSection.tsx
  src/components/user/ModalWrapper.tsx
  src/components/user/MyPageSection.tsx
  src/components/user/ProfileSection.tsx
  src/components/user/SectionBox.tsx
  src/components/user/Sidebar.tsx
  src/components/user/SidebarItem.tsx
  src/components/user/TermsBox.tsx
  src/components/user/TermsSection.tsx
  src/components/user/UserInfo.tsx
  src/components/user/UserInfoList.tsx
  src/components/user/UserProfileEdit.tsx
  src/components/user/Withdrawal.tsx
  src/components/user/ithdrawalComplete.tsx
  src/components/user/types.ts
Labels: ✨ Feature

#86 feat #76 : 챗봇 UI 구현
  src/app/(after)/layout.tsx
  src/components/chatbot/ChatbotChat.tsx
  src/components/chatbot/ChatbotContent.tsx
  src/components/chatbot/ChatbotHeader.tsx
  src/components/chatbot/ChatbotInput.tsx
  src/components/chatbot/ChatbotItem.tsx
  src/components/chatbot/ChatbotMain.tsx
  src/components/news/RecentNews.tsx
  src/constants.ts
  tailwind.config.ts
Labels: ✨ Feature

#88 feat #87 : Home 관심종목 UI 구현
  src/app/(after)/home/page.tsx
  src/components/favorite/FavoriteItem.tsx
  src/components/favorite/FavoriteMain.tsx
  src/constants.ts
Labels: ✨ Feature

#90 feat #89 : 챗봇 UI 스타일 적용 및 메세지 전송
  src/app/(after)/home/page.tsx
  src/components/chatbot/ChatbotContent.tsx
  src/components/chatbot/ChatbotHeader.tsx
  src/components/chatbot/ChatbotInput.tsx
  src/components/chatbot/ChatbotItem.tsx
  src/components/homefavorite/FavoriteItem.tsx
  src/components/homefavorite/FavoriteMain.tsx
Labels: ✨ Feature
