Repository NextCamp-8B/8B-SF, pull requests merged in 2024-07, with the labels that each got.

#92 refact # 91 : button 컴포넌트 수정
  src/app/(after)/layout.tsx
  src/components/news/NewsDetail.tsx
  src/components/shared/buttons/ButtonBase.tsx
  src/components/shared/buttons/FabButton.tsx
  src/components/shared/buttons/IconButton.tsx
  src/components/shared/buttons/IconButtonBase.tsx
  src/components/shared/buttons/LanguageButton.tsx
  src/components/shared/buttons/TextButton.tsx
  src/components/user/SectionBox.tsx
Labels: 🔨 Refactor

#94 feat #93 : supabase 함수 추가 types 폴더 추가
  .gitignore
  next.config.mjs
  src/types/news.ts
  src/utils/supabase/server.ts
Labels: ✨ Feature

#99 feat #95 : 뉴스 API 구현 1차 완료
  next.config.mjs
  src/app/(after)/news/[id]/page.tsx
  src/app/(after)/news/page.tsx
  src/app/api/news/related/stock/[id]/route.ts
  src/app/api/news/related/stock/route.ts
  src/components/news/HomeRelatedNews.tsx
  src/components/news/OriginNewsCard.tsx
  src/components/news/RelatedStock.tsx
  src/components/shared/Card.tsx
  src/components/shared/NewsListItem.tsx
  src/components/shared/StockIcon.tsx
  src/components/shared/StockListItem.tsx
  src/types/stock.ts
Labels: ✨ Feature

#105 feat #95 : 썸네일/ 로고 없을 시 상황 추가
  src/components/news/NewsDetail.tsx
  src/components/news/OriginNewsCard.tsx
  src/components/shared/Card.tsx
  src/components/shared/StockIcon.tsx
  src/types/news.ts
Labels: ✨ Feature

#107 feat #104 : Search 주식, 뉴스 데이터 연결
  src/app/api/search/news/route.ts
  src/app/api/search/stock/route.ts
  src/components/search/FindNews.tsx
  src/components/search/FindStock.tsx
  src/components/search/FindStockItem.tsx
  src/constants.ts
Labels: ✨ Feature

#112 feat #108 : 디바운스,api 변경, Card Link 추가 및 오류 수정
  src/app/api/search/news/route.ts
  src/app/api/search/stock/route.ts
  src/components/homefavorite/FavoriteItem.tsx
  src/components/recent/RecentItem.tsx
  src/components/search/FindNews.tsx
  src/components/search/FindStock.tsx
  src/components/search/FindStockItem.tsx
  src/components/search/NewsItem.tsx
  src/components/shared/Card.tsx
Labels: ✨ Feature

#113 refact : api code 수정
  src/app/api/search/stock/route.ts
Labels: 🔨 Refactor

#115 feat #114 : Skeleton UI Base
  src/app/(after)/news/[id]/page.tsx
  src/components/news/NewsDetail.tsx
  src/components/skeleton/Skeleton.tsx
  tailwind.config.ts
Labels: ✨ Feature

#119 feat #118 : StockListItem type related UI 추가
  src/components/shared/StockIcon.tsx
  src/components/shared/StockListItem.tsx
Labels: ✨ Feature

#123 fix #122 : 주가 소수점 미표기 수정
  src/components/shared/StockListItem.tsx
Labels: 🐞 BugFix

#128 refact #127 : 일반 회원가입 기능 수정
  src/components/signup/SignupForm.tsx
Labels: 🔨 Refactor

#140 refact #139 : 최신 뉴스 무한스크롤 렌더링 성능 개선
  src/app/(after)/news/page.tsx
  src/components/news/NewsBorder.tsx
  src/components/news/RecentNews.tsx
  src/components/shared/NewsListItem.tsx
Labels: 🔨 Refactor

#152 fix #151 : 임시 페이지 삭제
  src/app/(after)/news/[id]/page.tsx
  src/app/(after)/news/page.tsx
  src/app/(tmp)/han/page.tsx
  src/components/news/NewsDetail.tsx
  src/components/news/RecentNews.tsx
  src/components/skeleton/news/SkeletonNewsDetail.tsx
Labels: 🐞 BugFix

#155 feat #131 : 챗봇 기능 및 인기검색어
  src/app/(after)/search/page.tsx
  src/app/api/chatbot/route.ts
  src/app/api/search/popular/route.ts
  src/app/api/search/stock/route.ts
  src/components/chatbot/ChatbotChat.tsx
  src/components/chatbot/ChatbotContent.tsx
  src/components/chatbot/ChatbotInput.tsx
  src/components/chatbot/ChatbotItem.tsx
  src/components/search/FindStockItem.tsx
  src/components/search/InputItem.tsx
  src/components/search/PopularSearch.tsx
  src/components/search/SearchLabel.tsx
  src/components/skeleton/search/SkeletonPopularStock.tsx
  src/utils/llama.ts
Labels: ✨ Feature

#158 refact #157 : next-auth 유저 session 데이터 수정
  src/auth.ts
Labels: 🔨 Refactor

#163 feat #141 : 페이지 다국어 번역 기능
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/middleware.ts
  messages/zh.json
  next.config.mjs
  package.json
  src/app/[locale]/(after)/home/page.tsx
  src/app/[locale]/(after)/layout.tsx
  src/app/[locale]/(after)/news/[id]/page.tsx
  src/app/[locale]/(after)/news/page.tsx
  src/app/[locale]/(after)/search/page.tsx
  src/app/[locale]/(after)/stock/[stockId]/page.tsx
  src/app/[locale]/(after)/stock/interest/page.tsx
  src/app/[locale]/(after)/stock/page.tsx
  src/app/[locale]/(after)/user/page.tsx
  src/app/[locale]/(before)/find/id/page.tsx
  src/app/[locale]/(before)/find/pw/page.tsx
  src/app/[locale]/(before)/layout.tsx
  src/app/[locale]/(before)/login/error/page.tsx
  src/app/[locale]/(before)/login/page.tsx
  src/app/[locale]/(before)/signup/page.tsx
  src/app/[locale]/(before)/update-pw/page.tsx
  src/app/[locale]/(landing)/layout.tsx
  src/app/[locale]/(landing)/page.tsx
  src/app/[locale]/(tmp)/csh/page.tsx
  src/app/[locale]/(tmp)/example/page.tsx
  src/app/[locale]/(tmp)/hun/page.tsx
  src/i18n.ts
  src/middleware.ts
  yarn.lock
Labels: ✨ Feature

#165 feat #164 : 주식 페이지 추가
  src/app/[locale]/(after)/stock/page.tsx
  src/app/api/stock/decrease/route.ts
  src/app/api/stock/increase/route.ts
  src/app/api/stock/route.ts
  src/components/stock/AllStocks.tsx
  src/components/stock/LimitStocks.tsx
Labels: ✨ Feature

#169 feat #168 : StockListItem 스켈레톤 구현
  src/app/[locale]/(after)/stock/page.tsx
  src/components/skeleton/news/SkeletonRelatedStock.tsx
  src/components/skeleton/stock/SkeletonLimitStocks.tsx
  src/components/skeleton/stock/SkeletonStockListItem.tsx
  src/components/stock/AllStocks.tsx
  src/components/stock/LimitStocks.tsx
Labels: ✨ Feature

#171 feat #170 : i18n적용
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/middleware.ts
  messages/zh.json
  src/app/[locale]/(after)/news/[id]/page.tsx
  src/app/[locale]/(after)/news/page.tsx
  src/app/[locale]/(after)/stock/page.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/news/NewsDetail.tsx
Labels: ✨ Feature

#174 feat #173 : 랜딩 페이지 다국어 기능 추가
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/zh.json
  src/app/[locale]/(landing)/page.tsx
Labels: ✨ Feature

#177 feat #176 : Locale에 맞는 뉴스 번역
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/zh.json
  src/app/api/news/related/stock/[id]/route.ts
  src/components/news/HomeRecentNews.tsx
  src/components/news/HomeRelatedNews.tsx
  src/components/news/ImportantNews.tsx
  src/components/news/NewsDetail.tsx
  src/components/news/RecentNews.tsx
  src/components/news/RelatedNewsToNews.tsx
  src/components/news/RelatedNewsToStock.tsx
  src/components/shared/NewsListItem.tsx
  src/constants.ts
  src/types/news.d.ts
  src/types/next-auth.d.ts
  src/types/stock.d.ts
Labels: ✨ Feature

#182 refact #181 : 뉴스 번역 관련 로직 개선
  src/app/[locale]/(after)/news/[id]/page.tsx
  src/app/api/news/[id]/route.ts
  src/components/news/NewsDetail.tsx
  src/components/shared/IntlClientProvider.tsx
  src/components/shared/NewsListItem.tsx
  src/constants.ts
  src/utils/translate.ts
Labels: 🔨 Refactor

#185 refact #184 : news 조회수 IP 기준 추가
  src/app/api/news/[id]/route.ts
Labels: 🔨 Refactor

#188 feat #156 : Home 최근조회 추가
  src/app/api/home/recent/route.ts
  src/components/recent/Recent.tsx
  src/components/recent/RecentItem.tsx
  src/components/shared/StockListItem.tsx
  src/service/aightnowClient.ts
Labels: ✨ Feature

#191 fix #190 : StockListItem 스타일 수정
  src/components/shared/StockListItem.tsx
Labels: 🐞 BugFix

#193 feat #192 : 랜딩, 뉴스 페이지 metadata 추가
  src/app/[locale]/(after)/news/[id]/layout.tsx
  src/app/[locale]/(after)/news/layout.tsx
  src/app/favicon.ico
  src/app/layout.tsx
Labels: ✨ Feature

#195 refact #194 : fetch 로직 businessAPI로 이전
  src/app/[locale]/(after)/news/[id]/page.tsx
  src/app/api/news/related/stock/route.ts
  src/components/news/HomeNewsTab.tsx
  src/components/news/HomeRecentNews.tsx
  src/components/news/HomeRelatedNews.tsx
  src/components/news/ImportantNews.tsx
  src/components/news/NewsDetail.tsx
  src/components/news/RecentNews.tsx
  src/components/news/RelatedNewsToStock.tsx
  src/components/news/RelatedStock.tsx
  src/components/news/TodayPopularNews.tsx
  src/service/aightnowClient.ts
Labels: 🔨 Refactor

#200 feature #199 : 국제화 날짜 데이터 추가
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/zh.json
Labels: ✨ Feature

#203 refact : next/Image legacy 삭제
  src/app/[locale]/not-found.tsx
  src/components/shared/NewsListItem.tsx
Labels: 🔨 Refactor

#201 feat #198 : Card, Header, Search 국제화 작업
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/zh.json
  src/app/[locale]/(after)/search/page.tsx
  src/components/chatbot/ChatbotContent.tsx
  src/components/chatbot/ChatbotInput.tsx
  src/components/chatbot/ChatbotMain.tsx
  src/components/headers/HeadersNav.tsx
  src/components/recent/NoData.tsx
  src/components/recent/Recent.tsx
  src/components/search/DeleteSearch.tsx
  src/components/search/FindNews.tsx
  src/components/search/FindStock.tsx
  src/components/search/FindStockItem.tsx
  src/components/search/InputItem.tsx
  src/components/search/MoreData.tsx
  src/components/search/NewsItem.tsx
  src/components/search/NoSearchData.tsx
  src/components/search/NotFind.tsx
  src/components/search/PopularSearch.tsx
  src/components/search/RecentSearch.tsx
  src/components/shared/Card.tsx
  src/utils/date.ts
Labels: ✨ Feature

#205 refact #204 : message 메타데이터 추가
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/zh.json
  src/app/[locale]/(after)/news/layout.tsx
  src/app/[locale]/(tmp)/csh/page.tsx
  src/app/[locale]/(tmp)/example/page.tsx
  src/app/[locale]/(tmp)/hun/page.tsx
  src/app/[locale]/layout.tsx
  src/app/[locale]/loading.tsx
  src/app/api/layout.tsx
  src/app/layout.tsx
Labels: 🔨 Refactor

#207 feat #198 : search Layout 추가
  src/app/[locale]/(after)/search/layout.tsx
Labels: ✨ Feature

#208 refact : NewsListItem date변경
  src/app/[locale]/(after)/news/page.tsx
  src/app/api/news/[id]/route.ts
  src/components/news/HomeRecentNews.tsx
  src/components/news/HomeRelatedNews.tsx
  src/components/news/NewsDetail.tsx
  src/components/news/RecentNews.tsx
  src/components/news/RelatedNewsToNews.tsx
  src/components/news/RelatedNewsToStock.tsx
  src/components/shared/Card.tsx
  src/components/shared/NewsListItem.tsx
  src/service/aightnowClient.ts
Labels: 🔨 Refactor

#211 feat #209 : 한글 검색 추가
  src/app/api/search/stock/route.ts
Labels: ✨ Feature

#214 fix #213 : formattinPrice 표기 오류 수정
  src/utils/stock.ts
Labels: 🐞 BugFix

#222 refact #221 : StockListItem 삼항 연산자 개선
  src/components/shared/StockListItem.tsx
  src/utils/stock.ts
Labels: 🔨 Refactor

#224 fix #223 : 뉴스 조회 수 로직 dayjs utc 에러
  src/app/api/news/[id]/route.ts
Labels: 🐞 BugFix

#225 feat #218 : 로그인/회원가입/마이페이지 i18n 적용
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/zh.json
  src/app/[locale]/(after)/user/layout.tsx
  src/app/[locale]/(before)/find/id/page.tsx
  src/app/[locale]/(before)/find/pw/page.tsx
  src/app/[locale]/(before)/layout.tsx
  src/app/[locale]/(before)/login/error/page.tsx
  src/app/[locale]/(before)/login/page.tsx
  src/app/[locale]/(before)/update-pw/page.tsx
  src/app/api/reset/pw/route.ts
  src/components/findId/FindIdResult.tsx
  src/components/findPw/FindPwResult.tsx
  src/components/shared/ProfileDetails.tsx
  src/components/shared/buttons/LanguageButton.tsx
  src/components/signup/Agreement.tsx
  src/components/signup/Auth.tsx
  src/components/signup/Popup.tsx
  src/components/signup/ProfileSetup.tsx
  src/components/signup/SignupForm.tsx
  src/components/signup/Welcome.tsx
  src/components/user/CheckPassword.tsx
  src/components/user/ConfirmCanclePopup.tsx
  src/components/user/LanguageSection.tsx
  src/components/user/ProfileUpdated.tsx
  src/components/user/SectionAccount.tsx
  src/components/user/SectionProfile.tsx
  src/components/user/Sidebar.tsx
  src/components/user/SocialWithdrawal.tsx
  src/components/user/TermsBox.tsx
  src/components/user/TermsSection.tsx
  src/components/user/UserAccountEdit.tsx
  src/components/user/UserAccountForm.tsx
  src/components/user/UserInfo.tsx
  src/components/user/UserProfile.tsx
  src/components/user/Withdrawal.tsx
  src/components/user/WithdrawalComplete.tsx
  src/constants.ts
  src/hooks/user/useAccountUpdated.ts
  src/hooks/user/useCheckPw.ts
  src/hooks/user/useProfileUpdated.ts
  src/hooks/user/useUpdatePw.ts
  src/utils/user/updateUserData.ts
Labels: ✨ Feature

#229 feat #226 : 마이페이지 기능 개선 및 코드 수정
  src/app/[locale]/(after)/user/layout.tsx
  src/app/api/language/route.ts
  src/components/headers/HeadersNav.tsx
  src/components/shared/ProfileDetails.tsx
  src/components/skeleton/mypage/SkeletonLanguage.tsx
  src/components/user/LanguageSection.tsx
  src/components/user/SectionAccount.tsx
  src/components/user/SectionProfile.tsx
  src/components/user/SignoutButton.tsx
  src/components/user/UserAccountEdit.tsx
  src/hooks/user/useStockSelection.ts
Labels: 🔨 Refactor

#231 feat #230 : 실시간 환율 정보
  src/app/api/stock/exchange/route.ts
  src/components/shared/ToggleButton.tsx
  src/components/stock/StockDescription.tsx
  src/components/stock/detail/ChartSection.tsx
  src/service/aightnowClient.ts
  src/utils/stock.ts
Labels: ✨ Feature

#232 [#228] 담당 Component에 i18n 적용
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/zh.json
  src/app/[locale]/(after)/home/page.tsx
  src/app/[locale]/(after)/stock/[stockId]/page.tsx
  src/app/[locale]/(after)/stock/interest/layout.tsx
  src/app/[locale]/(after)/stock/interest/page.tsx
  src/components/home/AIReport.tsx
  src/components/home/ReportWrapper.tsx
  src/components/homefavorite/FavoriteMain.tsx
  src/components/shared/chart/SpecificStockAIReport.tsx
  src/components/shared/chart/StockAIReportCard.tsx
  src/components/shared/chart/StockAIReportChart.tsx
  src/components/shared/chart/StockChartCard.tsx
  src/components/shared/modal/ModalAddInterest.tsx
  src/components/stock/RequestWrapper.tsx
  src/components/stock/ThatGoAddInterest.tsx
  src/components/stock/detail/ChartSection.tsx
  src/components/stock/interest/Popular.tsx
  src/components/stock/interest/Recent.tsx
  src/components/stock/interest/Searched.tsx
Labels: ✨ Feature

#234 fix #233: ChartSection 컴포넌트 충돌 해결
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/zh.json
  src/components/stock/StockDescription.tsx
  src/components/stock/detail/AddInterest.tsx
  src/components/stock/detail/ChartSection.tsx
Labels: 🐞 BugFix

#236 feat #215 : chatbot openai 연결 및 스켈레톤 적용
  package.json
  src/app/api/chatbot/route.ts
  src/components/chatbot/ChatbotChat.tsx
  src/components/chatbot/ChatbotContent.tsx
  src/components/chatbot/ChatbotInput.tsx
  src/components/chatbot/ChatbotItem.tsx
  src/components/skeleton/chatbot/SkeletonChatbotContent.tsx
  src/utils/openai.ts
  yarn.lock
Labels: ✨ Feature

#238 feat #230 : 가격 DB 가격 반영
  src/components/stock/StockDescription.tsx
Labels: ✨ Feature

#242 [#241] 증권 거래소에 지정에 대한 네트워크 통신오류 해결
  src/app/api/stock/naverpay/duration/route.ts
  src/components/shared/chart/StockChartCard.tsx
  src/components/stock/detail/ChartSection.tsx
  src/service/aightnowClient.ts
Labels: 🐞 BugFix

#246 refact #245 : 환율 api 코드 개선
  src/app/api/stock/exchange/route.ts
Labels: 🔨 Refactor

#250 refact #249 : Stock 페이지 metadata 추가
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/zh.json
  src/app/[locale]/(after)/stock/layout.tsx
Labels: 🔨 Refactor

#252 마이페이지 metatadata 추가
  src/app/[locale]/(after)/user/layout.tsx
  src/app/[locale]/(before)/layout.tsx
  src/components/user/SectionAccount.tsx
  src/components/user/SocialWithdrawal.tsx
  src/components/user/Withdrawal.tsx
  src/components/user/WithdrawalForm.tsx
  src/hooks/user/useUpdatePw.ts
Labels: 🔨 Refactor

#254 [#253] Interest Layout에 Meta Title 적용
  src/app/[locale]/(after)/stock/interest/layout.tsx
  src/app/[locale]/(after)/stock/layout.tsx
Labels: ✨ Feature

#255 feat #240 : Home 디자인 변경 및 프롬프팅 수정
  src/components/chatbot/ChatbotContent.tsx
  src/components/homefavorite/FavoriteMain.tsx
  src/components/recent/Recent.tsx
  src/components/recent/RecentItem.tsx
  src/components/search/InputItem.tsx
  src/utils/openai.ts
Labels: ✨ Feature

#258 feat #256 : 챗봇 프롬프트 수정 및 최신 데이터 전달
  src/app/api/chatbot/route.ts
  src/components/chatbot/ChatbotContent.tsx
  src/components/chatbot/ChatbotInput.tsx
  src/components/search/InputItem.tsx
  src/utils/openai.ts
Labels: ✨ Feature

#261 fix #260 : ratio 계산 방식 수정
  src/utils/stock.ts
Labels: 🐞 BugFix

#263 fix #262 : build-error 해결
  src/app/api/stock/exchange/route.ts
Labels: 🌏 Deploy

#267 refact #266 : StockListItem 문자 정렬
  src/components/shared/StockListItem.tsx
Labels: 🔨 Refactor

#268 마이페이지 유저정보 수정/ 관심종목 기능 수정
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/zh.json
  src/app/api/mypage/profile/route.ts
  src/app/api/user/route.ts
  src/auth.ts
  src/components/shared/ProfileDetails.tsx
  src/components/signup/ProfileSetup.tsx
  src/components/signup/SignupForm.tsx
  src/components/skeleton/mypage/SkeletonProfileUpdated.tsx
  src/components/user/ProfileUpdated.tsx
  src/components/user/UserAccountEdit.tsx
  src/hooks/user/useAccountUpdated.ts
  src/hooks/user/useDuplicateCheck.ts
  src/hooks/user/useProfileUpdated.ts
  src/hooks/user/useStockSelection.ts
  src/types/next-auth.d.ts
  src/utils/supabase/supabaseHelper.ts
  src/utils/user/updateUserData.ts
Labels: ✨ Feature, 🔨 Refactor

#270 release #269 : 급상승, 급하락 종목 로직 수정
  src/app/api/stock/decrease/route.ts
  src/app/api/stock/increase/route.ts
  src/components/shared/StockListItem.tsx
  src/components/stock/LimitStocks.tsx
Labels: ✨ Feature

#273 input label, placeholder i18n 적용
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/zh.json
  src/components/shared/input/InputDuplicateCheck.tsx
  src/components/shared/input/InputValidated.tsx
  src/components/shared/input/inputConfig.ts
Labels: ✨ Feature

#275 release #274 : News 이미지 최적화
  next.config.mjs
  src/components/shared/NewsListItem.tsx
Labels: 🔨 Refactor

#276 Feature/prompt#256
  src/app/api/chatbot/route.ts
  src/app/api/chatbot/status/route.ts
  src/components/chatbot/ChatbotChat.tsx
  src/components/chatbot/ChatbotContent.tsx
  src/components/chatbot/ChatbotInput.tsx
  src/components/chatbot/ChatbotItem.tsx
  src/store/chatbotStore.ts
  src/utils/openai.ts
Labels: ✨ Feature

#278 refact #277 : 이미지 최적화
  src/components/search/NewsItem.tsx
  src/components/shared/Card.tsx
Labels: 🔨 Refactor

#280 refact #279 : 폰트 최적화
  src/app/[locale]/layout.tsx
  src/assets/fonts/subset-PretendardVariable-Regular.woff2
Labels: 🔨 Refactor

#282 refact #281 : 마이페이지 이미지, aria-label, sidebar 최적화
  src/app/[locale]/(after)/user/layout.tsx
  src/components/shared/ProfileDetails.tsx
  src/components/signup/Popup.tsx
  src/components/signup/ProfileImageEditor.tsx
  src/components/skeleton/mypage/SkeletonSidebar.tsx
  src/components/user/CommonSection.tsx
  src/components/user/ConfirmCanclePopup.tsx
  src/components/user/LanguageSection.tsx
  src/components/user/ProfileUpdated.tsx
  src/components/user/SidebarItem.tsx
  src/components/user/SocialWithdrawal.tsx
  src/components/user/UserAccountEdit.tsx
  src/components/user/UserAccountForm.tsx
  src/components/user/UserProfile.tsx
  src/components/user/Withdrawal.tsx
Labels: 🔨 Refactor

#284 뉴스 관련 주식 없을 때 UI 추가
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/zh.json
  src/components/news/RelatedStock.tsx
Labels: ✨ Feature

#286 관심종목 스켈레톤 UI 수정
  src/components/skeleton/shared/SkeletonWrapper.tsx
  src/components/stock/ShowingInterest.tsx
Labels: ✨ Feature

#289 refact #288 : 챗봇 수정
  messages/en.json
  messages/fr.json
  messages/ja.json
  messages/ko.json
  messages/zh.json
  src/components/chatbot/ChatbotContent.tsx
  src/components/chatbot/ChatbotInput.tsx
Labels: 🔨 Refactor

#295 refact #294 : StockIcon alt 추가
  src/components/shared/StockIcon.tsx
  src/components/shared/StockListItem.tsx
Labels: 🔨 Refactor

#296 feat #293 : 챗봇 기록 삭제 추가
  src/app/api/chatbot/route.ts
  src/components/chatbot/ChatbotChat.tsx
  src/components/chatbot/ChatbotContent.tsx
  src/store/chatbotStore.ts
Labels: ✨ Feature

#298 refact #297 : 차트 지표 약어로 수정
  messages/en.json
  messages/fr.json
Labels: 🔨 Refactor

#301 feat #300 : 챗봇 프롬프트 수정
  src/utils/openai.ts
Labels: ✨ Feature

#303 refact #302 : 챗봇 스켈레톤 수정
  src/components/chatbot/ChatbotChat.tsx
  src/components/chatbot/ChatbotContent.tsx
  src/components/chatbot/ChatbotInput.tsx
Labels: 🔨 Refactor

#305 refact #304 : 폰트 수정
  src/components/recent/NoData.tsx
  src/components/search/NotFind.tsx
Labels: 🔨 Refactor

#307 feature #306 : 마이페이지 수정
  src/components/user/ProfileUpdated.tsx
  src/components/user/UserAccountEdit.tsx
  src/components/user/UserAccountForm.tsx
Labels: ✨ Feature

#310 comparePrice 환율 미반영
  src/components/stock/StockDescription.tsx
  src/utils/stock.ts
Labels: 🐞 BugFix

#312 feat #311 : Card Link 경로 수정
  src/components/shared/Card.tsx
Labels: ✨ Feature

#313 [#308] 소통을 위한 2차 QA 피드백 반영
  src/components/stock/RequestWrapper.tsx
  src/components/stock/detail/ChartSection.tsx
Labels: 🔨 Refactor, 🌏 Deploy

#314 Release/csh qa issue3
  src/components/home/ReportWrapper.tsx
  src/components/stock/detail/ChartSection.tsx
Labels: 🔨 Refactor

#315 [#308] 소통을 위한 2차 QA 피드백 반영
  src/components/home/ReportWrapper.tsx
Labels: 🔨 Refactor
